version: "3.8"
services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_USER=root
      - DB_PASSWORD=yourpassword
      - DB_NAME=time_tracker
      - DB_HOST=db
      - DB_PORT=3306

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: time_tracker
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
